### ISSUE TITLE
vscode应用商店提示不支持vscode1.52.1版本

### ISSUE THREAD

**Issue by xby020** [JimFirst/naive-ui-snippets#1]
![image](https://user-images.githubusercontent.com/26197465/132791814-24e946a3-f1e7-4c5c-8e86-c03ae5b8578b.png)
见图

**Comment by JimFirst** [comment]
解决办法1. 升级本地vscode
2.把代码下载到本地，修改 package.json 
`"engines": {
	"vscode": "^1.52.1"
},`,
然后执行npm run build命令，本地安装生成的.vsix文件
